### PR TITLE
Use HTTPS instead of HTTP

### PR DESCRIPTION
**Pull request by elmotec**
- Merged 41eaa0b43c5eca7c from master (Factored root url in self.root_url and updated the root url to HTTPS instead of HTTP).
- Fixed conflict in test_fred.py by keeping the initial version (theirs). Fixed test as the popularity of releases appears to have changed.

### CODE REVIEW

**Comment by elmotec** [comment]
Hello @mortada, this is the HTTPS-only patch you requested. 

I had to look up the git docs and cherry-pick a specific commit from my master branch to my (new) https branch. I hope that's the right way to do this.

**Comment by mortada** [comment]
This looks good, thanks a lot!

**Comment by mortada** [comment]
Cherry-picking for this is good. Note that after I merge this PR your other PR will need to be rebased

**Comment by mortada** [comment]
This is a really minor thing but you might also want to make sure your commit has the same email as the email associated with your GitHub account. This way GitHub can link your commits to your username correctly. You can check that by looking at `git config user.email` locally

**Pull request merged**
